name: app-build

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: '1.20'
      node_version:
        required: false
        type: string
        default: '16'
      java_version:
        required: false
        type: string
        default: '11'
      ant_version:
        required: false
        type: string
        default: '1.10.8'
      java_tool_options:
        required: false
        type: string
        default: '-Dfile.encoding=UTF8'

jobs:
  run:
    runs-on: windows-latest
    env:
      GO_VERSION: ${{ inputs.go_version }}
      NODE_VERSION: ${{ inputs.node_version }}
      JAVA_VERSION: ${{ inputs.java_version }}
      ANT_VERSION: ${{ inputs.ant_version }}
      JAVA_TOOL_OPTIONS: ${{ inputs.java_tool_options }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      -
        name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      -
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ env.JAVA_VERSION }}
      -
        name: Set up ANT
        run: |
          choco install ant --no-progress --force -y --version $Env:ANT_VERSION
          $Env:PATH = "C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-$Env:ANT_VERSION\bin;$Env:PATH"
          echo "ANT_HOME=C:\ProgramData\chocolatey\lib\ant\tools\apache-ant-$Env:ANT_VERSION" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      -
        name: Java version
        run: |
          java -XshowSettings:properties -version
      -
        name: ANT version
        run: |
          ant -version
      -
        name: Node version
        run: |
          node --version
      -
        name: Config
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          echo "$(go env GOPATH)/bin/windows_386" >> $GITHUB_PATH

          echo "PORTAPPS_VERSION=$(cat go.mod | grep github.com/zeyac/gore | awk '{print $NF}')" >> $GITHUB_ENV
          echo "PORTAPPS_DIR=./.gore" >> $GITHUB_ENV

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "GIT_TAGNAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
        shell: bash
      -
        name: Checkout core
        uses: actions/checkout@v4
        with:
          repository: zeyac/gore
          ref: ${{ env.PORTAPPS_VERSION }}
          path: ${{ env.PORTAPPS_DIR }}
      -
        name: Build
        run: |
          ant release -Dcore.dir=${{ env.PORTAPPS_DIR }}
        shell: bash
      -
        name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: bin/release/*
      -
        name: GitHub Release
        uses: crazy-max/ghaction-github-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/release/*
          name: ${{ env.GIT_TAGNAME }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      -
        name: Dump context
        if: always()
        uses: crazy-max/ghaction-dump-context@v2
